"""Add user table

Revision ID: 509d41579da2
Revises: d81c8517b4c7
Create Date: 2023-08-30 17:30:33.174342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '509d41579da2'
down_revision = 'd81c8517b4c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False, unique=True),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
